import Head from 'next/head';
// import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Card from '../components/Card';
import DeckMenu from '../components/DeckMenu';
import Heading from '../components/Heading';
import { decks } from '../fixtures/decks';

export default function Home() {
  console.log('hello world')
  console.log(decks);
  return (
    <div className={styles.container}>
      <Head>
        <title>Reading Flashcards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading level="h1" title="Welcome to Reading Flashcards THing" />
        <Heading level="h2" title="My Decks" />
        <DeckMenu />
        <Heading level="h3" title="Current Deck Title" />
        <Card />
      </main>
    </div>
  )
}
